import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { PageHero } from "@/components/PageHero";

export const metadata: Metadata = {
  title: "Privacy Policy",
  alternates: { canonical: "/privacy" },
};

const LAST_UPDATED = "3 September 2026";
const CONTROLLER = "KGL Realty Pro";
const EMAIL = "hello@kglrealtypro.com";

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <PageHero
        label="Legal"
        title="Privacy Policy"
        description={`Last updated ${LAST_UPDATED}`}
        breadcrumbs={[{ label: "Privacy Policy", href: "/privacy" }]}
      />

      <main className="container py-16">
        <article className="prose prose-neutral mx-auto max-w-3xl dark:prose-invert">

          <h2>1. Who we are</h2>
          <p>
            {CONTROLLER} (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is a licensed real-estate
            agency registered in Nigeria and operating in Lagos, Abuja, Dubai (UAE), and the
            United Kingdom. We are the data controller for personal information collected
            through this website (<strong>kglrealtypro.com</strong>).
          </p>
          <p>
            Contact our data officer: <a href={`mailto:${EMAIL}`}>{EMAIL}</a>
          </p>

          <h2>2. What information we collect</h2>
          <p>We collect personal information only when you actively provide it or when it is generated by your use of our services:</p>
          <ul>
            <li><strong>Enquiry &amp; lead forms</strong> — name, phone number, email address, property interest, and budget.</li>
            <li><strong>Viewing requests</strong> — name, phone, email, preferred date and time, and the property slug.</li>
            <li><strong>AI concierge conversations</strong> — the text of messages you send to our concierge chat. These are processed by Anthropic (see section 5) and may be used to trigger lead capture or tour scheduling on your behalf.</li>
            <li><strong>Usage data</strong> — standard server logs including IP address, browser type, referral URL, and pages visited. This data is not linked to your identity.</li>
          </ul>

          <h2>3. How we use your information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Respond to property enquiries and schedule private viewings.</li>
            <li>Connect you with an appropriate agent or consultant.</li>
            <li>Send you property alerts or market updates, if you have opted in.</li>
            <li>Prevent fraud and abuse of our online services.</li>
            <li>Comply with legal obligations under Nigerian law (including the Nigeria Data Protection Act 2023) and, where applicable, the UK GDPR and UAE data protection regulations.</li>
          </ul>
          <p>
            We do <strong>not</strong> sell, rent, or trade your personal information to third parties for their own marketing purposes.
          </p>

          <h2>4. Legal basis for processing (GDPR / UK GDPR)</h2>
          <p>For users in the UK or European Economic Area, our legal bases are:</p>
          <ul>
            <li><strong>Contract performance</strong> — processing your enquiry or tour request.</li>
            <li><strong>Legitimate interests</strong> — responding to enquiries, preventing abuse, improving our services.</li>
            <li><strong>Consent</strong> — marketing communications (you may withdraw at any time).</li>
          </ul>

          <h2>5. Third-party service providers</h2>
          <p>We share limited data with the following providers, each bound by appropriate data processing agreements:</p>
          <ul>
            <li><strong>Anthropic, Inc.</strong> — powers our AI concierge. Conversation content is transmitted to Anthropic&apos;s API for processing. Anthropic&apos;s privacy policy is available at anthropic.com/privacy.</li>
            <li><strong>Vercel, Inc.</strong> — hosts this website and processes request logs.</li>
            <li><strong>Google LLC (Gmail)</strong> — used to deliver agent notification emails.</li>
            <li><strong>Cloudflare, Inc.</strong> — provides bot-protection challenges (Turnstile). Cloudflare may process IP addresses to verify requests.</li>
            <li><strong>Namecheap, Inc.</strong> — hosts our database on cPanel-managed infrastructure.</li>
          </ul>

          <h2>6. Data retention</h2>
          <ul>
            <li><strong>Leads and enquiries</strong> — retained for 24 months from the date of submission, then deleted unless a transaction is in progress.</li>
            <li><strong>Tour requests</strong> — retained for 12 months.</li>
            <li><strong>Server logs</strong> — retained for 90 days.</li>
            <li>You may request earlier deletion at any time (see section 8).</li>
          </ul>

          <h2>7. Cookies</h2>
          <p>
            This website uses only functional cookies: a currency preference cookie (stored in
            localStorage, not transmitted to our servers) and a theme preference cookie. We do
            not use advertising, tracking, or analytics cookies. No consent banner is required
            for strictly necessary functional cookies.
          </p>

          <h2>8. Your rights</h2>
          <p>Under the Nigeria Data Protection Act 2023 and, where applicable, the UK GDPR, you have the right to:</p>
          <ul>
            <li>Access a copy of the personal data we hold about you.</li>
            <li>Correct inaccurate data.</li>
            <li>Request deletion (&ldquo;right to be forgotten&rdquo;).</li>
            <li>Restrict or object to processing.</li>
            <li>Data portability (receive your data in a machine-readable format).</li>
            <li>Withdraw consent at any time without affecting prior processing.</li>
          </ul>
          <p>
            To exercise any of these rights, email us at{" "}
            <a href={`mailto:${EMAIL}`}>{EMAIL}</a> with the subject line &ldquo;Data Request&rdquo;.
            We will respond within 30 days.
          </p>

          <h2>9. Security</h2>
          <p>
            We implement appropriate technical and organisational measures to protect your
            personal data against unauthorised access, loss, or disclosure. All data is
            transmitted over HTTPS. Passwords (admin accounts) are stored as bcrypt hashes.
            Payment processing is not handled on this website.
          </p>

          <h2>10. International transfers</h2>
          <p>
            Because we operate in Nigeria, the UAE, and the UK, and use global cloud providers
            (Vercel, Anthropic, Google), your data may be processed outside your country of
            residence. Where data is transferred outside the UK or EEA, we rely on standard
            contractual clauses or adequacy decisions as the transfer mechanism.
          </p>

          <h2>11. Children&apos;s privacy</h2>
          <p>
            Our services are intended for adults. We do not knowingly collect personal data
            from anyone under the age of 18.
          </p>

          <h2>12. Changes to this policy</h2>
          <p>
            We may update this policy periodically. The &ldquo;Last updated&rdquo; date at the top of this
            page will reflect any changes. Continued use of the site after changes constitutes
            acceptance of the revised policy.
          </p>

          <h2>13. Contact &amp; complaints</h2>
          <p>
            For any privacy-related questions, contact us at{" "}
            <a href={`mailto:${EMAIL}`}>{EMAIL}</a>.
          </p>
          <p>
            UK users who are unsatisfied with our response may lodge a complaint with the
            Information Commissioner&apos;s Office (ICO) at <strong>ico.org.uk</strong>.
            Nigerian users may contact the Nigeria Data Protection Commission (NDPC) at{" "}
            <strong>ndpc.gov.ng</strong>.
          </p>

        </article>
      </main>
      <Footer />
    </>
  );
}
